version: "3.8"

services:

  db:
    container_name: postgresql_db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  # #celerystuff #user:guest password:guest
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  celery-worker:
    container_name: celery-worker
    build: .
    command: celery -A tasks worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - app
      - rabbitmq
    environment:
      CELERY_BROKER_URL: "amqp://rabbitmq"
      CELERY_RESULT_BACKEND: "db+postgresql://postgres:password@db:5432/air_quality_db"
      # CELERY_RESULT_BACKEND : "rpc://"
