"""sensor type properties

Revision ID: 17c347710975
Revises: af7466ab89ab
Create Date: 2023-02-07 14:46:09.857841

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '17c347710975'
down_revision = 'af7466ab89ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SensorTypes', sa.Column('properties', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SensorTypes', 'properties')
    # ### end Alembic commands ###
