"""added logs

Revision ID: 826507ee2016
Revises: c90ffd5a54f0
Create Date: 2022-09-13 13:15:41.548042

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '826507ee2016'
down_revision = 'c90ffd5a54f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Logs',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Logs')
    # ### end Alembic commands ###
