"""active_reason_property

Revision ID: 8c4b357a67eb
Revises: 17c347710975
Create Date: 2023-07-08 17:11:41.478226

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8c4b357a67eb'
down_revision = '17c347710975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sensors', sa.Column('active_reason', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sensors', 'active_reason')
    # ### end Alembic commands ###
