"""sensor_measurement_data

Revision ID: 9a8f3d4769b9
Revises: 8c4b357a67eb
Create Date: 2025-08-19 08:58:49.360885

"""

import os

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# load dotenv file
from dotenv import load_dotenv

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(BASE_DIR, ".env"))

# revision identifiers, used by Alembic.
revision = "9a8f3d4769b9"
down_revision = "8c4b357a67eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UnitsOfMeasurement",
        sa.Column("name", sa.String(), primary_key=True, nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )

    op.create_table(
        "ObservableProperties",
        sa.Column("name", sa.String(), primary_key=True, nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("datatype", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )

    op.create_table(
        "SensorPlatformTypeConfig",
        sa.Column("sensor_type_id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("authentication_url", sa.String(), nullable=True),
        sa.Column("authentication_method", sa.JSON(), nullable=True),
        sa.Column("api_url", sa.String(), nullable=False),
        sa.Column("api_method", sa.JSON(), nullable=False),
        sa.Column("sensor_mappings", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_type_id"],
            ["SensorTypes.id"],
        ),
        sa.PrimaryKeyConstraint("sensor_type_id"),
    )
    # ### end Alembic commands ###

    # insert some example units
    op.bulk_insert(
        sa.table(
            "UnitsOfMeasurement",
            sa.column("name", sa.String()),
            sa.column("url", sa.String()),
            sa.column("symbol", sa.String()),
        ),
        [
            {"name": "grams per cubic meter", "url": "http://qudt.org/vocab/unit/GRAM-PER-CUBIC-METER", "symbol": "g/m³"},
            {"name": "micrograms per m3", "url": "http://qudt.org/vocab/unit/MicroGM-PER-M3", "symbol": "µg/m³"},
            {"name": "degrees centigrade", "url": "http://qudt.org/vocab/unit/DEG_C", "symbol": "°"},
            {"name": "degrees kelvin", "url": "http://qudt.org/vocab/unit/KELVIN", "symbol": "K"},
            {"name": "percent", "url": "http://qudt.org/vocab/unit/PERCENT", "symbol": "%"},
            {"name": "pascal", "url": "http://qudt.org/vocab/unit/PA", "symbol": "Pa"},
            {"name": "decimal degree", "url": "http://qudt.org/vocab/unit/DEG", "symbol": "°"},
            {"name": "decibel", "url": "http://qudt.org/vocab/unit/DECIBEL", "symbol": "dB"},
            {"name": "parts per million", "url": "http://qudt.org/vocab/unit/PARTS-PER-MILLION", "symbol": "ppm"},
            {"name": "parts per billion", "url": "http://qudt.org/vocab/unit/PARTS-PER-BILLION", "symbol": "ppb"},
        ],
    )

    # insert some example observable properties
    op.bulk_insert(
        sa.table(
            "ObservableProperties",
            sa.column("name", sa.String()),
            sa.column("description", sa.String()),
            sa.column("url", sa.String()),
            sa.column("datatype", sa.String()),
        ),
        [
            {
                "name": "Timestamp",
                "description": "The UTC timestamp of the observation",
                "url": "http://www.w3.org/ns/sosa/resultTime",
                "datatype": "http://www.opengis.net/def/crs/OGC/0/.UnixTime-template",
            },
            {
                "name": "PM1",
                "description": "The amount of suspended particulates in the air with a diameter of 1 micrometer (μm) or less",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm1.0",
                "datatype": "float",
            },
            {
                "name": "PM1_A",
                "description": "The amount of suspended particulates in the air with a diameter of 1 micrometer (μm) or less, measured by sensor A",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm1.0",
                "datatype": "float",
            },
            {
                "name": "PM1_B",
                "description": "The amount of suspended particulates in the air with a diameter of 1 micrometer (μm) or less, measured by sensor B",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm1.0",
                "datatype": "float",
            },
            {
                "name": "PM1_A_Raw",
                "description": "The raw measurement of PM1 particles in the air, measured by sensor A",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm1-raw",
                "datatype": "float",
            },
            {
                "name": "PM1_B_Raw",
                "description": "The raw measurement of PM1 particles in the air, measured by sensor B",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm1-raw",
                "datatype": "float",
            },
            {
                "name": "PM1Raw",
                "description": "The raw measurement of PM1 particles in the air, without any corrections or adjustments",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm1-raw",
                "datatype": "float",
            },
            {
                "name": "PM2.5",
                "description": "The amount of suspended particulates in the air with a diameter of 2.5 micrometer (μm) or less.",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm2.5",
                "datatype": "float",
            },
            {
                "name": "PM2.5_A",
                "description": "The amount of suspended particulates in the air with a diameter of2.5 micrometer (μm) or less, measured by sensor A",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm2.5",
                "datatype": "float",
            },
            {
                "name": "PM2.5_B",
                "description": "The amount of suspended particulates in the air with a diameter of 2.5 micrometer (μm) or less, measured by sensor B",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm2.5",
                "datatype": "float",
            },
            {
                "name": "PM2.5_A_Raw",
                "description": "The raw measurement of PM2.5 particles in the air, measured by sensor A",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm2.5-raw",
                "datatype": "float",
            },
            {
                "name": "PM2.5_B_Raw",
                "description": "The raw measurement of PM2.5 particles in the air, measured by sensor B",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm2.5-raw",
                "datatype": "float",
            },
            {
                "name": "PM2.5Raw",
                "description": "The raw measurement of PM2.5 particles in the air, without any corrections or adjustments",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm2.5-raw",
                "datatype": "float",
            },
            {
                "name": "PM4",
                "description": "The amount of suspended particulates in the air with a diameter of 4 micrometer (μm) or less.",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm4",
                "datatype": "float",
            },
            {
                "name": "PM4_A",
                "description": "The amount of suspended particulates in the air with a diameter of 4 micrometer (μm) or less, measured by sensor A",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm4",
                "datatype": "float",
            },
            {
                "name": "PM4_B",
                "description": "The amount of suspended particulates in the air with a diameter of 4 micrometer (μm) or less, measured by sensor B",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm4",
                "datatype": "float",
            },
            {
                "name": "PM4_A_Raw",
                "description": "The raw measurement of PM4 particles in the air, measured by sensor A",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm4-raw",
                "datatype": "float",
            },
            {
                "name": "PM4_B_Raw",
                "description": "The raw measurement of PM4 particles in the air, measured by sensor B",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm4-raw",
                "datatype": "float",
            },
            {
                "name": "PM4Raw",
                "description": "The raw measurement of PM4 particles in the air, without any corrections or adjustments",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm4-raw",
                "datatype": "float",
            },
            {
                "name": "PM10",
                "description": "The amount of suspended particulates in the air with a diameter of 10 micrometer (μm) or less.",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm10",
                "datatype": "float",
            },
            {
                "name": "PM10_A",
                "description": "The amount of suspended particulates in the air with a diameter of 10 micrometer (μm) or less, measured by sensor A",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm10",
                "datatype": "float",
            },
            {
                "name": "PM10_B",
                "description": "The amount of suspended particulates in the air with a diameter of 10 micrometer (μm) or less, measured by sensor B",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm10",
                "datatype": "float",
            },
            {
                "name": "PM10_A_Raw",
                "description": "The raw measurement of PM10 particles in the air, measured by sensor A",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm10-raw",
                "datatype": "float",
            },
            {
                "name": "PM10_B_Raw",
                "description": "The raw measurement of PM10 particles in the air, measured by sensor B",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm10-raw",
                "datatype": "float",
            },
            {
                "name": "PM10Raw",
                "description": "The raw measurement of PM10 particles in the air, without any corrections or adjustments",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm10-raw",
                "datatype": "float",
            },
            {
                "name": "PM0.3Count",
                "description": "The count of particles in the air with a diameter of 0.3 micrometer (μm) or less",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pm0.3-count",
                "datatype": "float",
            },
            {
                "name": "CO",
                "description": "The quantity of Carbon monoxide in the air, which is a colorless, odorless gas that is produced by the incomplete combustion of carbon-containing fuels",
                "url": "https://w3id.org/ad4gd/air-quality/properties/co",
                "datatype": "float",
            },
            {
                "name": "NO",
                "description": "The quantity of Nitric oxide in the air, which is a colorless gas that is produced by the combustion of fossil fuels and is a precursor to nitrogen dioxide (NO2)",
                "url": "https://w3id.org/ad4gd/air-quality/properties/no",
                "datatype": "float",
            },
            {
                "name": "NO2",
                "description": "The quantity of Nitrogen dioxide in the air, which is a reddish-brown gas with a characteristic sharp, biting odor and is a significant air pollutant",
                "url": "https://w3id.org/ad4gd/air-quality/properties/no2",
                "datatype": "float",
            },
            {
                "name": "NOx",
                "description": "The quantity of Nitrogen oxides in the air, which is a group of gases that includes nitric oxide (NO) and nitrogen dioxide (NO2)",
                "url": "https://w3id.org/ad4gd/air-quality/properties/nox",
                "datatype": "float",
            },
            {
                "name": "NOxRaw",
                "description": "The raw measurement of Nitrogen oxides in the air, which is a group of gases that includes nitric oxide (NO) and nitrogen dioxide (NO2)",
                "url": "https://w3id.org/ad4gd/air-quality/properties/nox-raw",
                "datatype": "float",
            },
            {
                "name": "NOx Index",
                "description": "The index value of Nitrogen oxides in the air, which is a group of gases that includes nitric oxide (NO) and nitrogen dioxide (NO2)",
                "url": "https://w3id.org/ad4gd/air-quality/properties/nox-index",
                "datatype": "float",
            },
            {
                "name": "O3",
                "description": "The quantity of Ozone in the air, which is a pale blue gas with a sharp, pungent odor and is a significant air pollutant",
                "url": "https://w3id.org/ad4gd/air-quality/properties/o3",
                "datatype": "float",
            },
            {
                "name": "SO2",
                "description": "The quantity of Sulfur dioxide in the air, which is a colorless gas with a pungent odor and is a significant air pollutant",
                "url": "https://w3id.org/ad4gd/air-quality/properties/so2",
                "datatype": "float",
            },
            {
                "name": "VOC",
                "description": "The quantity of Volatile organic compounds in the air, which are a group of organic chemicals that can evaporate into the air and contribute to air pollution",
                "url": "https://w3id.org/ad4gd/air-quality/properties/voc",
                "datatype": "float",
            },
            {
                "name": "VOCRaw",
                "description": "The raw measurement of total Volatile Organic Compounds in the air, which is a group of organic chemicals that can evaporate into the air and contribute to air pollution",
                "url": "https://w3id.org/ad4gd/air-quality/properties/tvoc-raw",
                "datatype": "float",
            },
            {
                "name": "VOCIndex",
                "description": "The index value of total Volatile Organic Compounds in the air, which is a group of organic chemicals that can evaporate into the air and contribute to air pollution",
                "url": "https://w3id.org/ad4gd/air-quality/properties/tvoc-index",
                "datatype": "float",
            },
            {
                "name": "NoiseLAMax",
                "description": "The maximum sound level in decibels (dB) measured over a specified period of time",
                "url": "https://w3id.org/ad4gd/air-quality/properties/noise-la-max",
                "datatype": "float",
            },
            {
                "name": "NoiseLAMin",
                "description": "The minimum sound level in decibels (dB) measured over a specified period of time",
                "url": "https://w3id.org/ad4gd/air-quality/properties/noise-la-min",
                "datatype": "float",
            },
            {
                "name": "NoiseLAEq",
                "description": "The equivalent continuous sound level in decibels (dB) measured over a specified period of time",
                "url": "https://w3id.org/ad4gd/air-quality/properties/noise-la-eq",
                "datatype": "float",
            },
            {
                "name": "NoiseLAEqDelog",
                "description": "The equivalent continuous sound level in decibels (dB) measured over a specified period of time, with a logarithmic scale applied to the sound level",
                "url": "https://w3id.org/ad4gd/air-quality/properties/noise-la-eq-delog",
                "datatype": "float",
            },
            {
                "name": "Temperature",
                "description": "The average kinetic energy of the molecular motion in a substance and is defined in terms of a standard or calibrated thermometer in thermal equilibrium with the air",
                "url": "https://w3id.org/ad4gd/air-quality/properties/temperature",
                "datatype": "float",
            },
            {
                "name": "Humidity",
                "description": "A percentage that indicates how much water vapor is in the air relative to the maximum amount the air can hold at a given temperature.",
                "url": "https://w3id.org/ad4gd/air-quality/properties/humidity",
                "datatype": "float",
            },
            {
                "name": "Pressure",
                "description": "The force exerted per unit area by a fluid (liquid or gas) on a surface",
                "url": "https://w3id.org/ad4gd/air-quality/properties/pressure",
                "datatype": "float",
            },
            {
                "name": "RelativeHumidity",
                "description": "The amount of water vapor present in the air relative to the maximum amount the air can hold at a given temperature, expressed as a percentage",
                "url": "https://w3id.org/ad4gd/air-quality/properties/relative-humidity",
                "datatype": "float",
            },
            {
                "name": "RelativeTemperature",
                "description": "The temperature of the air relative to a reference temperature, typically the ambient temperature",
                "url": "https://w3id.org/ad4gd/air-quality/properties/relative-temperature",
                "datatype": "float",
            },
            {
                "name": "RelativePressure",
                "description": "The pressure of the air relative to a reference pressure, typically the ambient pressure",
                "url": "https://w3id.org/ad4gd/air-quality/properties/relative-pressure",
                "datatype": "float",
            },
            {
                "name": "AbsoluteTemperature",
                "description": "thermodynamic temperature is measured on an absolute scale where zero corresponds to absolute zero (the theoretical state at which particles have minimal thermal motion and no net heat energy can be extracted from the system)",
                "url": "https://w3id.org/ad4gd/air-quality/properties/absolute-temperature",
                "datatype": "float",
            },
            {
                "name": "AbsoluteHumidity",
                "description": "The amount of water vapor present in the air, which does not take temperature into account",
                "url": "https://w3id.org/ad4gd/air-quality/properties/absolute-humidity",
                "datatype": "float",
            },
            {
                "name": "AbsolutePressure",
                "description": "The total pressure exerted by a fluid, relative to a perfect vacuum",
                "url": "https://w3id.org/ad4gd/air-quality/properties/absolute-pressure",
                "datatype": "float",
            },
            {
                "name": "Longitude",
                "description": "WGS84 longitude of a point expressed in degrees, ranging from -180° to +180°",
                "url": "https://w3id.org/ad4gd/air-quality/properties/longitude",
                "datatype": "float",
            },
            {
                "name": "Latitude",
                "description": "WGS84 latitude of a point expressed in degrees, ranging from -90° to +90°",
                "url": "https://w3id.org/ad4gd/air-quality/properties/latitude",
                "datatype": "float",
            },
        ],
    )

    # TODO test 274237 purple air + the below
    # add a test generic sensor platform type ( generic air gradient sensor )
    op.bulk_insert(
        sa.table(
            "SensorTypes",
            sa.column("id", sa.Integer()),
            sa.column("name", sa.String()),
            sa.column("description", sa.String()),
            sa.column("properties", sa.JSON()),
        ),
        [
            {
                "id": -1,  # assuming -1 is the id for Air Gradient sensor type
                "name": "Generic-AG",
                "description": "A generic sensor type for Air Gradient sensors",
                "properties": {
                    "@context": "http://www.w3.org/ns/csvw",
                    "tableSchema": {
                        "columns": [
                            {"name": "timestamp", "titles": "The UTC timestamp of the observation", "propertyUrl": "https://www.w3.org/TR/xmlschema11-2/#dateTimeStamp", "datatype": "dateTimeStamp"},
                            {
                                "name": "PM1",
                                "titles": "The amount of suspended particulates in the air with a diameter of 1 micrometer (μm) or less. This measure has been humidity-corrected",
                                "http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure": {
                                    "@id": "http://qudt.org/vocab/unit/MicroGM-PER-M3",
                                    "rdfs:label": "micrograms per m3",
                                    "http://qudt.org/schema/qudt#symbol": "μg/m³",
                                },
                                "https://www.w3.org/TR/vocab-ssn/#SOSAusedProcedure": {"@id": "https://w3id.org/ad4gd/air-quality/procedures/pm-humidity-correction"},
                                "propertyUrl": "https://w3id.org/ad4gd/air-quality/properties/pm1.0",
                                "datatype": "float",
                            },
                        ]
                    },
                    "dialect": {"header": "true"},
                },
            }
        ],
    )

    # add a test generic sensor platform (generic air gradient sensor )
    op.bulk_insert(
        sa.table(
            "Sensors",
            sa.column("id", sa.Integer()),
            sa.column("lookup_id", sa.String()),
            sa.column("serial_number", sa.String()),
            sa.column("active", sa.Boolean()),
            sa.column("time_created", sa.DateTime(timezone=True)),
            sa.column("time_updated", sa.DateTime()),
            sa.column("stationary_box", geoalchemy2.types.Geometry(geometry_type="POLYGON", srid=4326, from_text="ST_GeomFromEWKT", name="geometry")),
            sa.column("user_id", sa.String()),
            sa.column("type_id", sa.Integer()),
        ),
        [
            {
                "id": -1,  # placeholder id for the generic sensor
                "type_id": -1,  # assuming 6 is the id for Air Gradient sensor type
                "lookup_id": "163763",  # test air gradient sensor
                "serial_number": "AG-1234567890",  # test serial number
                "active": True,
                "time_created": "2025-08-19 08:58:49.360885+00",  # current time
                "time_updated": None,
                "stationary_box": None,  # assuming no stationary box for this test sensor
                "user_id": None,  # assuming no user for this test sensor
            }
        ],
    )

    # add a test generic sensor type config (air gradient)
    op.bulk_insert(
        sa.table(
            "SensorPlatformTypeConfig",
            sa.column("sensor_type_id", sa.Integer()),
            sa.column("authentication_url", sa.String()),
            sa.column("authentication_method", sa.JSON()),
            sa.column("api_url", sa.String()),
            sa.column("api_method", sa.JSON()),
            sa.column("sensor_mappings", sa.JSON()),
        ),
        [
            {
                "sensor_type_id": -1,  # assuming 5 is the id for Air Gradient sensor type
                "authentication_url": None,
                "authentication_method": None,
                "api_url": "https://api.airgradient.com/public/api/v1/locations/{sensor_id}/measures/raw",
                "api_method": {
                    "auth_type": "url_token",
                    "token_key": "token",
                    "api_key_value": os.getenv("AIR_GRADIENT_API_KEY", "YOUR_API_KEY"),
                    "url_params": {"datetime_params": {"format": "%Y%m%dT%H%M%SZ", "start_key": "from", "end_key": "to"}},
                    "headers": {"Content-Type": "application/json"},
                },
                "sensor_mappings": {
                    "pm01": "PM1 Raw",
                    "pm25": "PM2.5 Raw",
                    "pm10": "PM10 Raw",
                    "pm01_corrected": "PM1",
                    "pm25_corrected": "PM2.5",
                    "pm10_corrected": "PM10",
                    "pm003Count": "PM0.3 Count",
                    "atmp_corrected": "Temperature",
                    "rhum_corrected": "Humidity",
                    "rco2": "CO2",
                    "tvoc": "VOC",
                    "tvocIndex": "VOC Index",
                    "noxIndex": "NOx Index",
                    "UTC Date/Time": "datetime",  # this is not needed as the date column will be inferred
                },
            }
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("SensorPlatformTypeConfig")
    op.drop_table("ObservableProperties")
    op.drop_table("UnitsOfMeasurement")
    # ### end Alembic commands ###
    op.execute('DELETE FROM "Sensors" WHERE id = -1')
    op.execute('DELETE FROM "SensorTypes" WHERE id = -1')
