"""New Migration

Revision ID: af7466ab89ab
Revises: 
Create Date: 2022-09-23 11:21:59.648710

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "af7466ab89ab"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Logs",
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "SensorTypes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Users",
        sa.Column("uid", sa.String(length=50), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_Users_uid"), "Users", ["uid"], unique=False)
    op.create_table(
        "Sensors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lookup_id", sa.String(length=50), nullable=True),
        sa.Column("serial_number", sa.String(length=50), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.Column(
            "stationary_box",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column("user_id", sa.String(length=50), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["SensorTypes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.uid"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_index(op.f("ix_Sensors_id"), "Sensors", ["id"], unique=False)
    op.create_table(
        "SensorSummaries",
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column("measurement_count", sa.Integer(), nullable=False),
        sa.Column("measurement_data", sa.JSON(), nullable=False),
        sa.Column("stationary", sa.Boolean(), nullable=False),
        sa.Column("sensor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["Sensors.id"],
        ),
        sa.PrimaryKeyConstraint("timestamp", "sensor_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("SensorSummaries")
    op.drop_index(op.f("ix_Sensors_id"), table_name="Sensors")

    op.drop_table("Sensors")
    op.drop_index(op.f("ix_Users_uid"), table_name="Users")
    op.drop_table("Users")
    op.drop_table("SensorTypes")
    op.drop_table("Logs")
    # ### end Alembic commands ###
