"""Table Refactoring

Revision ID: c2ca892aa6f6
Revises: 9a8f3d4769b9
Create Date: 2025-08-26 12:55:11.982285

"""

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c2ca892aa6f6"
down_revision = "9a8f3d4769b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_ObservableProperties_name"), "ObservableProperties", ["name"], unique=False)
    op.create_unique_constraint(None, "UnitsOfMeasurement", ["name"])
    op.alter_column("SensorTypes", "properties", new_column_name="sensor_metadata", existing_type=sa.JSON(), nullable=False)
    op.rename_table("SensorTypes", "SensorPlatformTypes")
    op.rename_table("Sensors", "SensorPlatforms")
    # # rename foreign keys
    # op.create_foreign_key(
    #     'SensorPlatforms_type_id_fkey',
    #     'SensorPlatforms', 'SensorPlatformTypes',
    #     ['type_id'], ['id']
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "UnitsOfMeasurement", type_="unique")
    op.drop_index(op.f("ix_ObservableProperties_name"), table_name="ObservableProperties")
    op.rename_table("SensorPlatformTypes", "SensorTypes")
    op.alter_column("SensorTypes", "sensor_metadata", new_column_name="properties", existing_type=sa.JSON(), nullable=False)
    op.rename_table("SensorPlatforms", "Sensors")
    # ### end Alembic commands ###
